{
  "formatVersion": "1.1",
  "component": {
    "group": "org.sweetchips",
    "module": "annotations",
    "version": "0.0.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "j6v7uxb7xjaz3kph5oztlftmfm"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "annotations-0.0.5.jar",
          "url": "annotations-0.0.5.jar",
          "size": 2348,
          "sha512": "63f8e1ccda77ef0b3e478efab95e13ead230c9ab177ebc8090d1fdff283330686bd78a48ab0d2059e8443b7ef9565c552dd9f438c86a1ba45d72aa0b24a3930d",
          "sha256": "b07e34bb6d9cede809e570db2eb640b4ff3177e1c788ecb807bfc04f704d2718",
          "sha1": "222753094218123c0462d006bc0054b594a5c62a",
          "md5": "db7808a9d91997177a49adabc06be5b5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "annotations-0.0.5.jar",
          "url": "annotations-0.0.5.jar",
          "size": 2348,
          "sha512": "63f8e1ccda77ef0b3e478efab95e13ead230c9ab177ebc8090d1fdff283330686bd78a48ab0d2059e8443b7ef9565c552dd9f438c86a1ba45d72aa0b24a3930d",
          "sha256": "b07e34bb6d9cede809e570db2eb640b4ff3177e1c788ecb807bfc04f704d2718",
          "sha1": "222753094218123c0462d006bc0054b594a5c62a",
          "md5": "db7808a9d91997177a49adabc06be5b5"
        }
      ]
    }
  ]
}
