{
  "formatVersion": "1.1",
  "component": {
    "group": "org.sweetchips",
    "module": "gradle-common",
    "version": "0.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "exroof3vsbfxhntlsu4bt3aai4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.sweetchips",
          "module": "platform-common",
          "version": {
            "requires": "0.0.2"
          }
        },
        {
          "group": "org.sweetchips",
          "module": "platform-jvm",
          "version": {
            "requires": "0.0.2"
          }
        }
      ],
      "files": [
        {
          "name": "gradle-common-0.0.2.jar",
          "url": "gradle-common-0.0.2.jar",
          "size": 13201,
          "sha512": "a1097d8692dca60a95061068a1735e37271169f942fe90c906bd361ed68f7e53ac28e30504d1c712ad384aaea93bb30c6618a30ca6a269afebab2aeef074e2dc",
          "sha256": "67719495a6407c25107f2c74a7dbdad49afd759aa866e302dce0a4046add6f47",
          "sha1": "953a6e29816fb876e01e82c2eafe797469733855",
          "md5": "e9a416a397996d40466d8ed97277764e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.sweetchips",
          "module": "utility",
          "version": {
            "requires": "0.0.2"
          }
        },
        {
          "group": "org.sweetchips",
          "module": "platform-common",
          "version": {
            "requires": "0.0.2"
          }
        },
        {
          "group": "org.sweetchips",
          "module": "platform-jvm",
          "version": {
            "requires": "0.0.2"
          }
        }
      ],
      "files": [
        {
          "name": "gradle-common-0.0.2.jar",
          "url": "gradle-common-0.0.2.jar",
          "size": 13201,
          "sha512": "a1097d8692dca60a95061068a1735e37271169f942fe90c906bd361ed68f7e53ac28e30504d1c712ad384aaea93bb30c6618a30ca6a269afebab2aeef074e2dc",
          "sha256": "67719495a6407c25107f2c74a7dbdad49afd759aa866e302dce0a4046add6f47",
          "sha1": "953a6e29816fb876e01e82c2eafe797469733855",
          "md5": "e9a416a397996d40466d8ed97277764e"
        }
      ]
    }
  ]
}
