{
  "formatVersion": "1.1",
  "component": {
    "group": "org.sweetchips",
    "module": "utility",
    "version": "0.0.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "iasetqhksbb2bf54g7ckmddd54"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "utility-0.0.6.jar",
          "url": "utility-0.0.6.jar",
          "size": 16674,
          "sha512": "1bdc3ec867d9fbb330aa09a459098ba7f97f9e8eceed76d72dbe6810ffb1096e8f400916dcc17da7e0e37896d5f88a6599770d0806b5b6ed816154149083141f",
          "sha256": "3f45a8cd6cda6fa73b82d171647d63e5565c51c229e3390e0b4f8fe2a6dbbfac",
          "sha1": "85c93fa461b135042aa5fb7bcb9c9dcf07f81894",
          "md5": "2d9d4315d0c863ca286c80d988f5a627"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "utility-0.0.6.jar",
          "url": "utility-0.0.6.jar",
          "size": 16674,
          "sha512": "1bdc3ec867d9fbb330aa09a459098ba7f97f9e8eceed76d72dbe6810ffb1096e8f400916dcc17da7e0e37896d5f88a6599770d0806b5b6ed816154149083141f",
          "sha256": "3f45a8cd6cda6fa73b82d171647d63e5565c51c229e3390e0b4f8fe2a6dbbfac",
          "sha1": "85c93fa461b135042aa5fb7bcb9c9dcf07f81894",
          "md5": "2d9d4315d0c863ca286c80d988f5a627"
        }
      ]
    }
  ]
}
