{
  "formatVersion": "1.1",
  "component": {
    "group": "org.sweetchips",
    "module": "plugin-recursive-tail",
    "version": "0.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "3q5f6fno4jauhkkdmwqgktgv5q"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "plugin-recursive-tail-0.0.1.jar",
          "url": "plugin-recursive-tail-0.0.1.jar",
          "size": 6356,
          "sha512": "7a1f487eb90aebae07a74a81ab396e10d180dd56f466567aa1741ba99ebc83459f2d6a6fbdd9058d66711fbbb5b56632d369d15621ab5d2a7cff9f3221adfdc7",
          "sha256": "4facf652f154579273a85550816bdda0aea13e4bbc0f6ffcfd0197a77e3d3b7a",
          "sha1": "8b23be8cb56a4fdd2b48aff2b4d27d3d4e4dd7ec",
          "md5": "6f4269c22b7d4e806463db636744159"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.sweetchips",
          "module": "utility",
          "version": {
            "requires": "0.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "plugin-recursive-tail-0.0.1.jar",
          "url": "plugin-recursive-tail-0.0.1.jar",
          "size": 6356,
          "sha512": "7a1f487eb90aebae07a74a81ab396e10d180dd56f466567aa1741ba99ebc83459f2d6a6fbdd9058d66711fbbb5b56632d369d15621ab5d2a7cff9f3221adfdc7",
          "sha256": "4facf652f154579273a85550816bdda0aea13e4bbc0f6ffcfd0197a77e3d3b7a",
          "sha1": "8b23be8cb56a4fdd2b48aff2b4d27d3d4e4dd7ec",
          "md5": "6f4269c22b7d4e806463db636744159"
        }
      ]
    }
  ]
}
