{
  "formatVersion": "1.1",
  "component": {
    "group": "org.sweetchips",
    "module": "utility",
    "version": "0.0.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "pwg5swrykbgklmld4ssy4wryza"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "utility-0.0.7.jar",
          "url": "utility-0.0.7.jar",
          "size": 16674,
          "sha512": "9c6a67414c03ff86c233713cfc9bbdfc5c0f52d7bd3563623c4067edd4a945ce924d8a3ad7cb2ae29656647d18bf07e5f8c48daf684ae4112d4733c1959a051c",
          "sha256": "b02d4ac0f2623b9721309648735086250eb22af9ceef645120acfae006a8378b",
          "sha1": "763628c74ea7514aaa4520a27d6e8388f3fb2612",
          "md5": "a4e66a70f985f99aeaf646c3639eb5a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "utility-0.0.7.jar",
          "url": "utility-0.0.7.jar",
          "size": 16674,
          "sha512": "9c6a67414c03ff86c233713cfc9bbdfc5c0f52d7bd3563623c4067edd4a945ce924d8a3ad7cb2ae29656647d18bf07e5f8c48daf684ae4112d4733c1959a051c",
          "sha256": "b02d4ac0f2623b9721309648735086250eb22af9ceef645120acfae006a8378b",
          "sha1": "763628c74ea7514aaa4520a27d6e8388f3fb2612",
          "md5": "a4e66a70f985f99aeaf646c3639eb5a"
        }
      ]
    }
  ]
}
