{
  "formatVersion": "1.1",
  "component": {
    "group": "org.sweetchips",
    "module": "plugin-trace-weaver",
    "version": "0.0.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "j6v7uxb7xjaz3kph5oztlftmfm"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "plugin-trace-weaver-0.0.5.jar",
          "url": "plugin-trace-weaver-0.0.5.jar",
          "size": 19159,
          "sha512": "9d46dbbb098675eeda9cc92a594de3d0c72a1f02fc5fd77806149563538d467bb9c9e9636c7463a65b17bb644fe882a12c7d766df1a85223f8dd440fb224e5b2",
          "sha256": "d7d98e2c7c322b96f67c075630e35cd81072a1523f20456de027f7b174032cc2",
          "sha1": "c5ef6b69e741b060f66e186e8f80077802c4330",
          "md5": "7ec0cb75198ec881302ea92d393c7d2c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.sweetchips",
          "module": "utility",
          "version": {
            "requires": "0.0.5"
          }
        }
      ],
      "files": [
        {
          "name": "plugin-trace-weaver-0.0.5.jar",
          "url": "plugin-trace-weaver-0.0.5.jar",
          "size": 19159,
          "sha512": "9d46dbbb098675eeda9cc92a594de3d0c72a1f02fc5fd77806149563538d467bb9c9e9636c7463a65b17bb644fe882a12c7d766df1a85223f8dd440fb224e5b2",
          "sha256": "d7d98e2c7c322b96f67c075630e35cd81072a1523f20456de027f7b174032cc2",
          "sha1": "c5ef6b69e741b060f66e186e8f80077802c4330",
          "md5": "7ec0cb75198ec881302ea92d393c7d2c"
        }
      ]
    }
  ]
}
