{
  "formatVersion": "1.1",
  "component": {
    "group": "org.sweetchips",
    "module": "plugin-annotations-visitors",
    "version": "0.0.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "pwg5swrykbgklmld4ssy4wryza"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "plugin-annotations-visitors-0.0.7.jar",
          "url": "plugin-annotations-visitors-0.0.7.jar",
          "size": 9417,
          "sha512": "16fe0ebb6e1f60047fb1219f8315eb5cef76b0e0a5354792cd388a1de54f8c0b8b81994b2484792a7910733f15e2459f3cebd568b0b55d7793cf458305490c34",
          "sha256": "81d22fb13b7580fd600b6a0c30be6f3b685b99ae561bb8cd76895166c36306d8",
          "sha1": "accb5c0dea24622ce3634977b88bf408befbbfb9",
          "md5": "8a532f789c7130983fe2e8d880d33650"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.sweetchips",
          "module": "utility",
          "version": {
            "requires": "0.0.7"
          }
        },
        {
          "group": "org.sweetchips",
          "module": "annotations",
          "version": {
            "requires": "0.0.7"
          }
        }
      ],
      "files": [
        {
          "name": "plugin-annotations-visitors-0.0.7.jar",
          "url": "plugin-annotations-visitors-0.0.7.jar",
          "size": 9417,
          "sha512": "16fe0ebb6e1f60047fb1219f8315eb5cef76b0e0a5354792cd388a1de54f8c0b8b81994b2484792a7910733f15e2459f3cebd568b0b55d7793cf458305490c34",
          "sha256": "81d22fb13b7580fd600b6a0c30be6f3b685b99ae561bb8cd76895166c36306d8",
          "sha1": "accb5c0dea24622ce3634977b88bf408befbbfb9",
          "md5": "8a532f789c7130983fe2e8d880d33650"
        }
      ]
    }
  ]
}
